### ISSUE TITLE
Provincia

### ISSUE THREAD

**Issue by ioliasa** [FzrFernando/ProgramacionTercerTrimestre#1]
En existePueblo, si encuentras el pueblo deberías salirte del bucle.

En delPueblo, si encuentras el pueblo borras el siguiente????

En delPueblo, setSuperficie, setNúmeroHabitantes, getInformacionPueblo no te sales si lo encuentras.

En listadoNombresPueblos y listadoPueblos deberías usar un StringBuilder en vez de un String

**Comment by FzrFernando** [comment]
Corregido, pero con dudas a la hora de salirme del bucle

**Comment by ioliasa** [comment]
Fernando recuerdame que mañana lo vemos en clase y te explico lo de salirte del bucle

**Comment by ioliasa** [comment]
No está corregido, recuérdame que lo veamos mañana en clase

**Comment by FzrFernando** [comment]
Acabo de subir un arreglo que he hecho en Provincia

**Comment by ioliasa** [comment]
Fernando o no me has actualizado el repositorio o no te has enterado

**Comment by FzrFernando** [comment]
Es posible que ya esté arreglado
