### ISSUE TITLE
Realizado Correción del Examen

### ISSUE THREAD

**Issue by FzrFernando** [FzrFernando/ProgramacionTercerTrimestre#7]
Se encuentra en ZamoraRicoFernandoPrueba19Mayo

**Comment by ioliasa** [comment]
Temporada. anadirCapituloDespues: no controlas la exception de que no exista el capítulo que estás buscando. 
Series: modificarTema. Sigues con esto mal "No compruebas si el tema es el mismo". Además ¿qué pasa si no está la serie?

**Comment by FzrFernando** [comment]
Listo para corrección
